# Generated by Django 5.2.6 on 2025-10-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
