# Generated by Django 5.2.7 on 2025-10-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_up', '0002_alter_usercontent_url_alter_usercontent_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontent',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='QrCode',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='URL',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='video',
        ),
        migrations.AddField(
            model_name='usercontent',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontent',
            name='url',
            field=models.URLField(default='https://docs.google.com/document/d/1ilA0kqiqzcQbXYuwovItyuxNVYkjM0aaPH52z6ZegD8/edit?tab=t.0'),
            preserve_default=False,
        ),
    ]
