# Generated by Django 5.2.6 on 2025-09-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("image", models.ImageField(upload_to="qr_codes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
