# Generated by Django 5.2.6 on 2025-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='qr_codes/'),
        ),
    ]
