# Generated by Django 5.2.6 on 2025-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='image',
        ),
        migrations.AddField(
            model_name='url',
            name='image_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
