# Generated by Django 5.2.6 on 2025-09-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_url_image_url_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
