# Generated by Django 5.2.7 on 2025-10-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_url_description_alter_url_image_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
    ]
